# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@localhost/chirpstack_as?sslmode=disable"

[redis]
url="redis://localhost:6379"

[application_server.integration.mqtt]
server="tcp://localhost:1883"

[application_server.api]
public_host="localhost:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="clearfeverminesmicro"
